package hotelbooking.CorbaInterface;


/**
* CHotelServerInterface/_CIHotelServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public class _CIHotelServerStub extends org.omg.CORBA.portable.ObjectImpl implements hotelbooking.CorbaInterface.CIHotelServer
{

  public int getProfile (hotelbooking.CorbaInterface.CHotelProfileHolder profile)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getProfile", true);
                $in = _invoke ($out);
                int $result = hotelbooking.CorbaInterface.CERROR_CODEHelper.read ($in);
                profile.value = hotelbooking.CorbaInterface.CHotelProfileHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getProfile (profile        );
            } finally {
                _releaseReply ($in);
            }
  } // getProfile

  public int reserveHotel (String guestID, hotelbooking.CorbaInterface.CRoomType roomType, hotelbooking.CorbaInterface.CDate checkInDate, hotelbooking.CorbaInterface.CDate checkOutDate, int reservationID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("reserveHotel", true);
                $out.write_string (guestID);
                hotelbooking.CorbaInterface.CRoomTypeHelper.write ($out, roomType);
                hotelbooking.CorbaInterface.CDateHelper.write ($out, checkInDate);
                hotelbooking.CorbaInterface.CDateHelper.write ($out, checkOutDate);
                hotelbooking.CorbaInterface.CReserveIDHelper.write ($out, reservationID);
                $in = _invoke ($out);
                int $result = hotelbooking.CorbaInterface.CERROR_CODEHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return reserveHotel (guestID, roomType, checkInDate, checkOutDate, reservationID        );
            } finally {
                _releaseReply ($in);
            }
  } // reserveHotel

  public int cancelHotel (String guestID, hotelbooking.CorbaInterface.CRoomType roomType, hotelbooking.CorbaInterface.CDate checkInDate, hotelbooking.CorbaInterface.CDate checkOutDate)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cancelHotel", true);
                $out.write_string (guestID);
                hotelbooking.CorbaInterface.CRoomTypeHelper.write ($out, roomType);
                hotelbooking.CorbaInterface.CDateHelper.write ($out, checkInDate);
                hotelbooking.CorbaInterface.CDateHelper.write ($out, checkOutDate);
                $in = _invoke ($out);
                int $result = hotelbooking.CorbaInterface.CERROR_CODEHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cancelHotel (guestID, roomType, checkInDate, checkOutDate        );
            } finally {
                _releaseReply ($in);
            }
  } // cancelHotel

  public int checkAvailability (String guestID, hotelbooking.CorbaInterface.CRoomType roomType, hotelbooking.CorbaInterface.CDate checkInDate, hotelbooking.CorbaInterface.CDate checkOutDate, hotelbooking.CorbaInterface.CListAvailabilityHolder listAvail)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("checkAvailability", true);
                $out.write_string (guestID);
                hotelbooking.CorbaInterface.CRoomTypeHelper.write ($out, roomType);
                hotelbooking.CorbaInterface.CDateHelper.write ($out, checkInDate);
                hotelbooking.CorbaInterface.CDateHelper.write ($out, checkOutDate);
                $in = _invoke ($out);
                int $result = hotelbooking.CorbaInterface.CERROR_CODEHelper.read ($in);
                listAvail.value = hotelbooking.CorbaInterface.CListAvailabilityHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return checkAvailability (guestID, roomType, checkInDate, checkOutDate, listAvail        );
            } finally {
                _releaseReply ($in);
            }
  } // checkAvailability

  public int getManagerObject (String manageID, String passCode, hotelbooking.CorbaInterface.CIHotelServerManagerHolder serverManager)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getManagerObject", true);
                $out.write_string (manageID);
                $out.write_string (passCode);
                $in = _invoke ($out);
                int $result = hotelbooking.CorbaInterface.CERROR_CODEHelper.read ($in);
                serverManager.value = hotelbooking.CorbaInterface.CIHotelServerManagerHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getManagerObject (manageID, passCode, serverManager        );
            } finally {
                _releaseReply ($in);
            }
  } // getManagerObject

  public int transferReservation (String guestID, int reservationID, hotelbooking.CorbaInterface.CRoomType roomType, hotelbooking.CorbaInterface.CDate checkInDate, hotelbooking.CorbaInterface.CDate checkOutDate, String targetHotel, int newResID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("transferReservation", true);
                $out.write_string (guestID);
                hotelbooking.CorbaInterface.CReserveIDHelper.write ($out, reservationID);
                hotelbooking.CorbaInterface.CRoomTypeHelper.write ($out, roomType);
                hotelbooking.CorbaInterface.CDateHelper.write ($out, checkInDate);
                hotelbooking.CorbaInterface.CDateHelper.write ($out, checkOutDate);
                $out.write_string (targetHotel);
                hotelbooking.CorbaInterface.CReserveIDHelper.write ($out, newResID);
                $in = _invoke ($out);
                int $result = hotelbooking.CorbaInterface.CERROR_CODEHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return transferReservation (guestID, reservationID, roomType, checkInDate, checkOutDate, targetHotel, newResID        );
            } finally {
                _releaseReply ($in);
            }
  } // transferReservation

  public int addQuerySockets (hotelbooking.CorbaInterface.CINetSocketAddress[] sockets)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addQuerySockets", true);
                hotelbooking.CorbaInterface.CListSocketsHelper.write ($out, sockets);
                $in = _invoke ($out);
                int $result = hotelbooking.CorbaInterface.CERROR_CODEHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addQuerySockets (sockets        );
            } finally {
                _releaseReply ($in);
            }
  } // addQuerySockets

  public int deleteQuerySockets (hotelbooking.CorbaInterface.CINetSocketAddress[] sockets)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deleteQuerySockets", true);
                hotelbooking.CorbaInterface.CListSocketsHelper.write ($out, sockets);
                $in = _invoke ($out);
                int $result = hotelbooking.CorbaInterface.CERROR_CODEHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return deleteQuerySockets (sockets        );
            } finally {
                _releaseReply ($in);
            }
  } // deleteQuerySockets

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CHotelServerInterface/CIHotelServer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CIHotelServerStub
