package hotelbooking.CorbaInterface;


/**
* CHotelServerInterface/CAvailabilityHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

abstract public class CAvailabilityHelper
{
  private static String  _id = "IDL:CHotelServerInterface/CAvailability:1.0";

  public static void insert (org.omg.CORBA.Any a, hotelbooking.CorbaInterface.CAvailability that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static hotelbooking.CorbaInterface.CAvailability extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "hotelName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
          _members0[1] = new org.omg.CORBA.StructMember (
            "availCount",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[2] = new org.omg.CORBA.StructMember (
            "rate",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (hotelbooking.CorbaInterface.CAvailabilityHelper.id (), "CAvailability", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static hotelbooking.CorbaInterface.CAvailability read (org.omg.CORBA.portable.InputStream istream)
  {
    hotelbooking.CorbaInterface.CAvailability value = new hotelbooking.CorbaInterface.CAvailability ();
    value.hotelName = istream.read_string ();
    value.availCount = istream.read_ushort ();
    value.rate = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, hotelbooking.CorbaInterface.CAvailability value)
  {
    ostream.write_string (value.hotelName);
    ostream.write_ushort (value.availCount);
    ostream.write_float (value.rate);
  }

}
