package hotelbooking.CorbaInterface;

/**
* CHotelServerInterface/CAvailabilityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public final class CAvailabilityHolder implements org.omg.CORBA.portable.Streamable
{
  public hotelbooking.CorbaInterface.CAvailability value = null;

  public CAvailabilityHolder ()
  {
  }

  public CAvailabilityHolder (hotelbooking.CorbaInterface.CAvailability initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hotelbooking.CorbaInterface.CAvailabilityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hotelbooking.CorbaInterface.CAvailabilityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hotelbooking.CorbaInterface.CAvailabilityHelper.type ();
  }

}
