package hotelbooking.CorbaInterface;


/**
* CHotelServerInterface/CIHotelServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public interface CIHotelServerOperations 
{
  int getProfile (hotelbooking.CorbaInterface.CHotelProfileHolder profile);
  int reserveHotel (String guestID, hotelbooking.CorbaInterface.CRoomType roomType, hotelbooking.CorbaInterface.CDate checkInDate, hotelbooking.CorbaInterface.CDate checkOutDate, int reservationID);
  int cancelHotel (String guestID, hotelbooking.CorbaInterface.CRoomType roomType, hotelbooking.CorbaInterface.CDate checkInDate, hotelbooking.CorbaInterface.CDate checkOutDate);
  int checkAvailability (String guestID, hotelbooking.CorbaInterface.CRoomType roomType, hotelbooking.CorbaInterface.CDate checkInDate, hotelbooking.CorbaInterface.CDate checkOutDate, hotelbooking.CorbaInterface.CListAvailabilityHolder listAvail);
  int getManagerObject (String manageID, String passCode, hotelbooking.CorbaInterface.CIHotelServerManagerHolder serverManager);
  int transferReservation (String guestID, int reservationID, hotelbooking.CorbaInterface.CRoomType roomType, hotelbooking.CorbaInterface.CDate checkInDate, hotelbooking.CorbaInterface.CDate checkOutDate, String targetHotel, int newResID);
  int addQuerySockets (hotelbooking.CorbaInterface.CINetSocketAddress[] sockets);
  int deleteQuerySockets (hotelbooking.CorbaInterface.CINetSocketAddress[] sockets);
} // interface CIHotelServerOperations
