package hotelbooking.CorbaInterface;

/**
* CHotelServerInterface/CIHotelServerManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public final class CIHotelServerManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public hotelbooking.CorbaInterface.CIHotelServerManager value = null;

  public CIHotelServerManagerHolder ()
  {
  }

  public CIHotelServerManagerHolder (hotelbooking.CorbaInterface.CIHotelServerManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hotelbooking.CorbaInterface.CIHotelServerManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hotelbooking.CorbaInterface.CIHotelServerManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hotelbooking.CorbaInterface.CIHotelServerManagerHelper.type ();
  }

}
