package hotelbooking.CorbaInterface;


/**
* CHotelServerInterface/CIHotelServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public abstract class CIHotelServerPOA extends org.omg.PortableServer.Servant
 implements hotelbooking.CorbaInterface.CIHotelServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getProfile", new java.lang.Integer (0));
    _methods.put ("reserveHotel", new java.lang.Integer (1));
    _methods.put ("cancelHotel", new java.lang.Integer (2));
    _methods.put ("checkAvailability", new java.lang.Integer (3));
    _methods.put ("getManagerObject", new java.lang.Integer (4));
    _methods.put ("transferReservation", new java.lang.Integer (5));
    _methods.put ("addQuerySockets", new java.lang.Integer (6));
    _methods.put ("deleteQuerySockets", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CHotelServerInterface/CIHotelServer/getProfile
       {
         hotelbooking.CorbaInterface.CHotelProfileHolder profile = new hotelbooking.CorbaInterface.CHotelProfileHolder ();
         int $result = (int)0;
         $result = this.getProfile (profile);
         out = $rh.createReply();
         out.write_long ($result);
         hotelbooking.CorbaInterface.CHotelProfileHelper.write (out, profile.value);
         break;
       }

       case 1:  // CHotelServerInterface/CIHotelServer/reserveHotel
       {
         String guestID = in.read_string ();
         hotelbooking.CorbaInterface.CRoomType roomType = hotelbooking.CorbaInterface.CRoomTypeHelper.read (in);
         hotelbooking.CorbaInterface.CDate checkInDate = hotelbooking.CorbaInterface.CDateHelper.read (in);
         hotelbooking.CorbaInterface.CDate checkOutDate = hotelbooking.CorbaInterface.CDateHelper.read (in);
         int reservationID = hotelbooking.CorbaInterface.CReserveIDHelper.read (in);
         int $result = (int)0;
         $result = this.reserveHotel (guestID, roomType, checkInDate, checkOutDate, reservationID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // CHotelServerInterface/CIHotelServer/cancelHotel
       {
         String guestID = in.read_string ();
         hotelbooking.CorbaInterface.CRoomType roomType = hotelbooking.CorbaInterface.CRoomTypeHelper.read (in);
         hotelbooking.CorbaInterface.CDate checkInDate = hotelbooking.CorbaInterface.CDateHelper.read (in);
         hotelbooking.CorbaInterface.CDate checkOutDate = hotelbooking.CorbaInterface.CDateHelper.read (in);
         int $result = (int)0;
         $result = this.cancelHotel (guestID, roomType, checkInDate, checkOutDate);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // CHotelServerInterface/CIHotelServer/checkAvailability
       {
         String guestID = in.read_string ();
         hotelbooking.CorbaInterface.CRoomType roomType = hotelbooking.CorbaInterface.CRoomTypeHelper.read (in);
         hotelbooking.CorbaInterface.CDate checkInDate = hotelbooking.CorbaInterface.CDateHelper.read (in);
         hotelbooking.CorbaInterface.CDate checkOutDate = hotelbooking.CorbaInterface.CDateHelper.read (in);
         hotelbooking.CorbaInterface.CListAvailabilityHolder listAvail = new hotelbooking.CorbaInterface.CListAvailabilityHolder ();
         int $result = (int)0;
         $result = this.checkAvailability (guestID, roomType, checkInDate, checkOutDate, listAvail);
         out = $rh.createReply();
         out.write_long ($result);
         hotelbooking.CorbaInterface.CListAvailabilityHelper.write (out, listAvail.value);
         break;
       }

       case 4:  // CHotelServerInterface/CIHotelServer/getManagerObject
       {
         String manageID = in.read_string ();
         String passCode = in.read_string ();
         hotelbooking.CorbaInterface.CIHotelServerManagerHolder serverManager = new hotelbooking.CorbaInterface.CIHotelServerManagerHolder ();
         int $result = (int)0;
         $result = this.getManagerObject (manageID, passCode, serverManager);
         out = $rh.createReply();
         out.write_long ($result);
         hotelbooking.CorbaInterface.CIHotelServerManagerHelper.write (out, serverManager.value);
         break;
       }

       case 5:  // CHotelServerInterface/CIHotelServer/transferReservation
       {
         String guestID = in.read_string ();
         int reservationID = hotelbooking.CorbaInterface.CReserveIDHelper.read (in);
         hotelbooking.CorbaInterface.CRoomType roomType = hotelbooking.CorbaInterface.CRoomTypeHelper.read (in);
         hotelbooking.CorbaInterface.CDate checkInDate = hotelbooking.CorbaInterface.CDateHelper.read (in);
         hotelbooking.CorbaInterface.CDate checkOutDate = hotelbooking.CorbaInterface.CDateHelper.read (in);
         String targetHotel = in.read_string ();
         int newResID = hotelbooking.CorbaInterface.CReserveIDHelper.read (in);
         int $result = (int)0;
         $result = this.transferReservation (guestID, reservationID, roomType, checkInDate, checkOutDate, targetHotel, newResID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // CHotelServerInterface/CIHotelServer/addQuerySockets
       {
         hotelbooking.CorbaInterface.CINetSocketAddress sockets[] = hotelbooking.CorbaInterface.CListSocketsHelper.read (in);
         int $result = (int)0;
         $result = this.addQuerySockets (sockets);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 7:  // CHotelServerInterface/CIHotelServer/deleteQuerySockets
       {
         hotelbooking.CorbaInterface.CINetSocketAddress sockets[] = hotelbooking.CorbaInterface.CListSocketsHelper.read (in);
         int $result = (int)0;
         $result = this.deleteQuerySockets (sockets);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CHotelServerInterface/CIHotelServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CIHotelServer _this() 
  {
    return CIHotelServerHelper.narrow(
    super._this_object());
  }

  public CIHotelServer _this(org.omg.CORBA.ORB orb) 
  {
    return CIHotelServerHelper.narrow(
    super._this_object(orb));
  }


} // class CIHotelServerPOA
