package hotelbooking.CorbaInterface;


/**
* CHotelServerInterface/CIHotelServerManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public interface CIHotelServerManagerOperations 
{
  int getServiceReport (hotelbooking.CorbaInterface.CDate serviceDate, hotelbooking.CorbaInterface.CListRecordHolder records);
  int getStatusReport (hotelbooking.CorbaInterface.CDate serviceDate, hotelbooking.CorbaInterface.CListRecordHolder records);
  int getRecordsSnapshot (hotelbooking.CorbaInterface.CListRecordHolder records);
} // interface CIHotelServerManagerOperations
