package hotelbooking.CorbaInterface;

/**
* CHotelServerInterface/CINetSocketAddressHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public final class CINetSocketAddressHolder implements org.omg.CORBA.portable.Streamable
{
  public hotelbooking.CorbaInterface.CINetSocketAddress value = null;

  public CINetSocketAddressHolder ()
  {
  }

  public CINetSocketAddressHolder (hotelbooking.CorbaInterface.CINetSocketAddress initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hotelbooking.CorbaInterface.CINetSocketAddressHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hotelbooking.CorbaInterface.CINetSocketAddressHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hotelbooking.CorbaInterface.CINetSocketAddressHelper.type ();
  }

}
