package hotelbooking.CorbaInterface;


/**
* CHotelServerInterface/CListRecordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public final class CListRecordHolder implements org.omg.CORBA.portable.Streamable
{
  public hotelbooking.CorbaInterface.CRecord value[] = null;

  public CListRecordHolder ()
  {
  }

  public CListRecordHolder (hotelbooking.CorbaInterface.CRecord[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hotelbooking.CorbaInterface.CListRecordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hotelbooking.CorbaInterface.CListRecordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hotelbooking.CorbaInterface.CListRecordHelper.type ();
  }

}
