package hotelbooking.CorbaInterface;


/**
* CHotelServerInterface/CRoomTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/


// And a convertion utilitity is designed to convert them back and forth
abstract public class CRoomTypeHelper
{
  private static String  _id = "IDL:CHotelServerInterface/CRoomType:1.0";

  public static void insert (org.omg.CORBA.Any a, hotelbooking.CorbaInterface.CRoomType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static hotelbooking.CorbaInterface.CRoomType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (hotelbooking.CorbaInterface.CRoomTypeHelper.id (), "CRoomType", new String[] { "ROOM_SINGLE", "ROOM_DOUBLE", "ROOM_FAMILY"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static hotelbooking.CorbaInterface.CRoomType read (org.omg.CORBA.portable.InputStream istream)
  {
    return hotelbooking.CorbaInterface.CRoomType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, hotelbooking.CorbaInterface.CRoomType value)
  {
    ostream.write_long (value.value ());
  }

}
