package hotelbooking.CorbaInterface;


/**
* CHotelServerInterface/CRoomType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/


// And a convertion utilitity is designed to convert them back and forth
public class CRoomType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static hotelbooking.CorbaInterface.CRoomType[] __array = new hotelbooking.CorbaInterface.CRoomType [__size];

  public static final int _ROOM_SINGLE = 0;
  public static final hotelbooking.CorbaInterface.CRoomType ROOM_SINGLE = new hotelbooking.CorbaInterface.CRoomType(_ROOM_SINGLE);
  public static final int _ROOM_DOUBLE = 1;
  public static final hotelbooking.CorbaInterface.CRoomType ROOM_DOUBLE = new hotelbooking.CorbaInterface.CRoomType(_ROOM_DOUBLE);
  public static final int _ROOM_FAMILY = 2;
  public static final hotelbooking.CorbaInterface.CRoomType ROOM_FAMILY = new hotelbooking.CorbaInterface.CRoomType(_ROOM_FAMILY);

  public int value ()
  {
    return __value;
  }

  public static hotelbooking.CorbaInterface.CRoomType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CRoomType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CRoomType
