package hotelbooking.CorbaInterface;

/**
* CHotelServerInterface/CRoomTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/


// And a convertion utilitity is designed to convert them back and forth
public final class CRoomTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public hotelbooking.CorbaInterface.CRoomType value = null;

  public CRoomTypeHolder ()
  {
  }

  public CRoomTypeHolder (hotelbooking.CorbaInterface.CRoomType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hotelbooking.CorbaInterface.CRoomTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hotelbooking.CorbaInterface.CRoomTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hotelbooking.CorbaInterface.CRoomTypeHelper.type ();
  }

}
