package hotelbooking.CorbaInterface;


/**
* CHotelServerInterface/IHotelCentralAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Monday, October 26, 2015 6:38:21 PM EDT
*/

public interface IHotelCentralAdminOperations 
{
  int registerServer (hotelbooking.CorbaInterface.CIHotelServer server, hotelbooking.CorbaInterface.CINetSocketAddress socket);
  int unregisterServer (hotelbooking.CorbaInterface.CIHotelServer server);
} // interface IHotelCentralAdminOperations
