
package client.webservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelServerWSService", targetNamespace = "http://serverws/", wsdlLocation = "META-INF/wsdl/HotelServerWSService.wsdl")
public class HotelServerWSService
    extends Service
{

    private final static URL HOTELSERVERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELSERVERWSSERVICE_EXCEPTION;
    private final static QName HOTELSERVERWSSERVICE_QNAME = new QName("http://serverws/", "HotelServerWSService");

    static {
        HOTELSERVERWSSERVICE_WSDL_LOCATION = client.webservice.HotelServerWSService.class.getClassLoader().getResource("META-INF/wsdl/HotelServerWSService.wsdl");
        WebServiceException e = null;
        if (HOTELSERVERWSSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/HotelServerWSService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        HOTELSERVERWSSERVICE_EXCEPTION = e;
    }

    public HotelServerWSService() {
        super(__getWsdlLocation(), HOTELSERVERWSSERVICE_QNAME);
    }

    public HotelServerWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELSERVERWSSERVICE_QNAME, features);
    }

    public HotelServerWSService(URL wsdlLocation) {
        super(wsdlLocation, HOTELSERVERWSSERVICE_QNAME);
    }

    public HotelServerWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELSERVERWSSERVICE_QNAME, features);
    }

    public HotelServerWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelServerWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelServerWS
     */
    @WebEndpoint(name = "HotelServerWSPort")
    public HotelServerWS getHotelServerWSPort() {
        return super.getPort(new QName("http://serverws/", "HotelServerWSPort"), HotelServerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelServerWS
     */
    @WebEndpoint(name = "HotelServerWSPort")
    public HotelServerWS getHotelServerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serverws/", "HotelServerWSPort"), HotelServerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELSERVERWSSERVICE_EXCEPTION!= null) {
            throw HOTELSERVERWSSERVICE_EXCEPTION;
        }
        return HOTELSERVERWSSERVICE_WSDL_LOCATION;
    }

}
