package CHotelServerInterface;


/**
* CHotelServerInterface/_CIHotelServerManagerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Friday, November 27, 2015 4:40:26 AM EST
*/

public class _CIHotelServerManagerStub extends org.omg.CORBA.portable.ObjectImpl implements CHotelServerInterface.CIHotelServerManager
{

  public int getServiceReport (CHotelServerInterface.CDate serviceDate, CHotelServerInterface.CListRecordHolder records)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getServiceReport", true);
                CHotelServerInterface.CDateHelper.write ($out, serviceDate);
                $in = _invoke ($out);
                int $result = CHotelServerInterface.CERROR_CODEHelper.read ($in);
                records.value = CHotelServerInterface.CListRecordHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getServiceReport (serviceDate, records        );
            } finally {
                _releaseReply ($in);
            }
  } // getServiceReport

  public int getStatusReport (CHotelServerInterface.CDate serviceDate, CHotelServerInterface.CListRecordHolder records)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getStatusReport", true);
                CHotelServerInterface.CDateHelper.write ($out, serviceDate);
                $in = _invoke ($out);
                int $result = CHotelServerInterface.CERROR_CODEHelper.read ($in);
                records.value = CHotelServerInterface.CListRecordHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getStatusReport (serviceDate, records        );
            } finally {
                _releaseReply ($in);
            }
  } // getStatusReport

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CHotelServerInterface/CIHotelServerManager:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CIHotelServerManagerStub
