package CHotelServerInterface;


/**
* CHotelServerInterface/_CIHotelCentralAdminStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Tuesday, October 27, 2015 12:11:22 PM EDT
*/

public class _CIHotelCentralAdminStub extends org.omg.CORBA.portable.ObjectImpl implements CHotelServerInterface.CIHotelCentralAdmin
{

  public int registerServer (CHotelServerInterface.CIHotelServer server, CHotelServerInterface.CINetSocketAddress socket)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerServer", true);
                CHotelServerInterface.CIHotelServerHelper.write ($out, server);
                CHotelServerInterface.CINetSocketAddressHelper.write ($out, socket);
                $in = _invoke ($out);
                int $result = CHotelServerInterface.CERROR_CODEHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registerServer (server, socket        );
            } finally {
                _releaseReply ($in);
            }
  } // registerServer

  public int unregisterServer (CHotelServerInterface.CIHotelServer server)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("unregisterServer", true);
                CHotelServerInterface.CIHotelServerHelper.write ($out, server);
                $in = _invoke ($out);
                int $result = CHotelServerInterface.CERROR_CODEHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return unregisterServer (server        );
            } finally {
                _releaseReply ($in);
            }
  } // unregisterServer

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CHotelServerInterface/CIHotelCentralAdmin:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CIHotelCentralAdminStub
