package CHotelServerInterface;


/**
* CHotelServerInterface/arrHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Monday, October 26, 2015 3:29:58 PM EDT
*/

abstract public class arrHelper
{
  private static String  _id = "IDL:CHotelServerInterface/arr:1.0";

  public static void insert (org.omg.CORBA.Any a, CHotelServerInterface.CAvailability[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CHotelServerInterface.CAvailability[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = CHotelServerInterface.CAvailabilityHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_array_tc (10, __typeCode );
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CHotelServerInterface.arrHelper.id (), "arr", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CHotelServerInterface.CAvailability[] read (org.omg.CORBA.portable.InputStream istream)
  {
    CHotelServerInterface.CAvailability value[] = null;
    value = new CHotelServerInterface.CAvailability[10];
    for (int _o0 = 0;_o0 < (10); ++_o0)
    {
      value[_o0] = CHotelServerInterface.CAvailabilityHelper.read (istream);
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CHotelServerInterface.CAvailability[] value)
  {
    if (value.length != (10))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (10); ++_i0)
    {
      CHotelServerInterface.CAvailabilityHelper.write (ostream, value[_i0]);
    }
  }

}
