package CHotelServerInterface;


/**
* CHotelServerInterface/CDate.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Friday, November 27, 2015 4:40:26 AM EST
*/

public final class CDate implements org.omg.CORBA.portable.IDLEntity
{
  public short year = (short)0;
  public short month = (short)0;
  public short day = (short)0;

  public CDate ()
  {
  } // ctor

  public CDate (short _year, short _month, short _day)
  {
    year = _year;
    month = _month;
    day = _day;
  } // ctor

} // class CDate
