package CHotelServerInterface;

/**
* CHotelServerInterface/CDateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public final class CDateHolder implements org.omg.CORBA.portable.Streamable
{
  public CHotelServerInterface.CDate value = null;

  public CDateHolder ()
  {
  }

  public CDateHolder (CHotelServerInterface.CDate initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CHotelServerInterface.CDateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CHotelServerInterface.CDateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CHotelServerInterface.CDateHelper.type ();
  }

}
