package CHotelServerInterface;


/**
* CHotelServerInterface/CHotelProfileHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

abstract public class CHotelProfileHelper
{
  private static String  _id = "IDL:CHotelServerInterface/CHotelProfile:1.0";

  public static void insert (org.omg.CORBA.Any a, CHotelServerInterface.CHotelProfile that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CHotelServerInterface.CHotelProfile extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "shortName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "fullName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "descText",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "totalRooms",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "rates",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CHotelServerInterface.CHotelProfileHelper.id (), "CHotelProfile", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CHotelServerInterface.CHotelProfile read (org.omg.CORBA.portable.InputStream istream)
  {
    CHotelServerInterface.CHotelProfile value = new CHotelServerInterface.CHotelProfile ();
    value.shortName = istream.read_string ();
    value.fullName = istream.read_string ();
    value.descText = istream.read_string ();
    int _len0 = istream.read_long ();
    value.totalRooms = new short[_len0];
    istream.read_short_array (value.totalRooms, 0, _len0);
    int _len1 = istream.read_long ();
    value.rates = new float[_len1];
    istream.read_float_array (value.rates, 0, _len1);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CHotelServerInterface.CHotelProfile value)
  {
    ostream.write_string (value.shortName);
    ostream.write_string (value.fullName);
    ostream.write_string (value.descText);
    ostream.write_long (value.totalRooms.length);
    ostream.write_short_array (value.totalRooms, 0, value.totalRooms.length);
    ostream.write_long (value.rates.length);
    ostream.write_float_array (value.rates, 0, value.rates.length);
  }

}
