package CHotelServerInterface;


/**
* CHotelServerInterface/CIHotelCentralAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Tuesday, October 27, 2015 12:11:22 PM EDT
*/

public interface CIHotelCentralAdmin extends CIHotelCentralAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CIHotelCentralAdmin
