package CHotelServerInterface;


/**
* CHotelServerInterface/CIHotelServerManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Tuesday, October 27, 2015 12:11:22 PM EDT
*/

public abstract class CIHotelServerManagerPOA extends org.omg.PortableServer.Servant
 implements CHotelServerInterface.CIHotelServerManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getServiceReport", new java.lang.Integer (0));
    _methods.put ("getStatusReport", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CHotelServerInterface/CIHotelServerManager/getServiceReport
       {
         CHotelServerInterface.CDate serviceDate = CHotelServerInterface.CDateHelper.read (in);
         CHotelServerInterface.CListRecordHolder records = new CHotelServerInterface.CListRecordHolder ();
         int $result = (int)0;
         $result = this.getServiceReport (serviceDate, records);
         out = $rh.createReply();
         out.write_long ($result);
         CHotelServerInterface.CListRecordHelper.write (out, records.value);
         break;
       }

       case 1:  // CHotelServerInterface/CIHotelServerManager/getStatusReport
       {
         CHotelServerInterface.CDate serviceDate = CHotelServerInterface.CDateHelper.read (in);
         CHotelServerInterface.CListRecordHolder records = new CHotelServerInterface.CListRecordHolder ();
         int $result = (int)0;
         $result = this.getStatusReport (serviceDate, records);
         out = $rh.createReply();
         out.write_long ($result);
         CHotelServerInterface.CListRecordHelper.write (out, records.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CHotelServerInterface/CIHotelServerManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CIHotelServerManager _this() 
  {
    return CIHotelServerManagerHelper.narrow(
    super._this_object());
  }

  public CIHotelServerManager _this(org.omg.CORBA.ORB orb) 
  {
    return CIHotelServerManagerHelper.narrow(
    super._this_object(orb));
  }


} // class CIHotelServerManagerPOA
