package CHotelServerInterface;


/**
* CHotelServerInterface/CIHotelServerManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public interface CIHotelServerManagerOperations 
{
  int getServiceReport (CHotelServerInterface.CDate serviceDate, CHotelServerInterface.CListRecordHolder records);
  int getStatusReport (CHotelServerInterface.CDate serviceDate, CHotelServerInterface.CListRecordHolder records);
  int getRecordsSnapshot (CHotelServerInterface.CListRecordHolder records);
} // interface CIHotelServerManagerOperations
