package CHotelServerInterface;


/**
* CHotelServerInterface/CIHotelServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Tuesday, October 27, 2015 12:11:22 PM EDT
*/

public interface CIHotelServerOperations 
{
  int getProfile (CHotelServerInterface.CHotelProfileHolder profile);
  int reserveHotel (String guestID, CHotelServerInterface.CRoomType roomType, CHotelServerInterface.CDate checkInDate, CHotelServerInterface.CDate checkOutDate, org.omg.CORBA.IntHolder reservationID);
  int cancelHotel (String guestID, CHotelServerInterface.CRoomType roomType, CHotelServerInterface.CDate checkInDate, CHotelServerInterface.CDate checkOutDate);
  int checkAvailability (String guestID, CHotelServerInterface.CRoomType roomType, CHotelServerInterface.CDate checkInDate, CHotelServerInterface.CDate checkOutDate, CHotelServerInterface.CListAvailabilityHolder listAvail);
  int getManagerObject (String manageID, String passCode, CHotelServerInterface.CIHotelServerManagerHolder serverManager);
  int transferReservation (String guestID, int reservationID, CHotelServerInterface.CRoomType roomType, CHotelServerInterface.CDate checkInDate, CHotelServerInterface.CDate checkOutDate, String targetHotel, org.omg.CORBA.IntHolder newResID);
  int addQuerySockets (CHotelServerInterface.CINetSocketAddress[] sockets);
  int deleteQuerySockets (CHotelServerInterface.CINetSocketAddress[] sockets);
} // interface CIHotelServerOperations
