package CHotelServerInterface;


/**
* CHotelServerInterface/CIHotelServerManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Friday, November 27, 2015 4:40:26 AM EST
*/

public interface CIHotelServerManagerOperations 
{
  int getServiceReport (CHotelServerInterface.CDate serviceDate, CHotelServerInterface.CListRecordHolder records);
  int getStatusReport (CHotelServerInterface.CDate serviceDate, CHotelServerInterface.CListRecordHolder records);
} // interface CIHotelServerManagerOperations
