package CHotelServerInterface;


/**
* CHotelServerInterface/CIHotelServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public interface CIHotelServerOperations 
{
  int getProfile (CHotelServerInterface.CHotelProfileHolder profile);
  int reserveHotel (String guestID, CHotelServerInterface.CRoomType roomType, CHotelServerInterface.CDate checkInDate, CHotelServerInterface.CDate checkOutDate, int reservationID);
  int cancelHotel (String guestID, CHotelServerInterface.CRoomType roomType, CHotelServerInterface.CDate checkInDate, CHotelServerInterface.CDate checkOutDate);
  int checkAvailability (String guestID, CHotelServerInterface.CRoomType roomType, CHotelServerInterface.CDate checkInDate, CHotelServerInterface.CDate checkOutDate, CHotelServerInterface.CListAvailabilityHolder listAvail);
  int getManagerObject (String manageID, String passCode, CHotelServerInterface.CIHotelServerManagerHolder serverManager);
  int transferReservation (String guestID, int reservationID, CHotelServerInterface.CRoomType roomType, CHotelServerInterface.CDate checkInDate, CHotelServerInterface.CDate checkOutDate, String targetHotel, int newResID);
  int addQuerySockets (CHotelServerInterface.CINetSocketAddress[] sockets);
  int deleteQuerySockets (CHotelServerInterface.CINetSocketAddress[] sockets);
} // interface CIHotelServerOperations
