package CHotelServerInterface;


/**
* CHotelServerInterface/CIHotelCentralAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Friday, November 27, 2015 4:40:26 AM EST
*/

public interface CIHotelCentralAdmin extends CIHotelCentralAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CIHotelCentralAdmin
