package CHotelServerInterface;


/**
* CHotelServerInterface/CIHotelCentralAdminPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public abstract class CIHotelCentralAdminPOA extends org.omg.PortableServer.Servant
 implements CHotelServerInterface.CIHotelCentralAdminOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerServer", new java.lang.Integer (0));
    _methods.put ("unregisterServer", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CHotelServerInterface/CIHotelCentralAdmin/registerServer
       {
         CHotelServerInterface.CIHotelServer server = CHotelServerInterface.CIHotelServerHelper.read (in);
         CHotelServerInterface.CINetSocketAddress socket = CHotelServerInterface.CINetSocketAddressHelper.read (in);
         int $result = (int)0;
         $result = this.registerServer (server, socket);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // CHotelServerInterface/CIHotelCentralAdmin/unregisterServer
       {
         CHotelServerInterface.CIHotelServer server = CHotelServerInterface.CIHotelServerHelper.read (in);
         int $result = (int)0;
         $result = this.unregisterServer (server);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CHotelServerInterface/CIHotelCentralAdmin:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CIHotelCentralAdmin _this() 
  {
    return CIHotelCentralAdminHelper.narrow(
    super._this_object());
  }

  public CIHotelCentralAdmin _this(org.omg.CORBA.ORB orb) 
  {
    return CIHotelCentralAdminHelper.narrow(
    super._this_object(orb));
  }


} // class CIHotelCentralAdminPOA
