package CHotelServerInterface;


/**
* CHotelServerInterface/CIHotelCentralAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public interface CIHotelCentralAdmin extends CIHotelCentralAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CIHotelCentralAdmin
