package CHotelServerInterface;


/**
* CHotelServerInterface/CINetSocketAddress.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Tuesday, October 27, 2015 12:11:22 PM EDT
*/

public final class CINetSocketAddress implements org.omg.CORBA.portable.IDLEntity
{
  public String host = null;
  public short port = (short)0;

  public CINetSocketAddress ()
  {
  } // ctor

  public CINetSocketAddress (String _host, short _port)
  {
    host = _host;
    port = _port;
  } // ctor

} // class CINetSocketAddress
