package CHotelServerInterface;


/**
* CHotelServerInterface/CINetSocketAddressHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

abstract public class CINetSocketAddressHelper
{
  private static String  _id = "IDL:CHotelServerInterface/CINetSocketAddress:1.0";

  public static void insert (org.omg.CORBA.Any a, CHotelServerInterface.CINetSocketAddress that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CHotelServerInterface.CINetSocketAddress extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "host",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
          _members0[1] = new org.omg.CORBA.StructMember (
            "port",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CHotelServerInterface.CINetSocketAddressHelper.id (), "CINetSocketAddress", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CHotelServerInterface.CINetSocketAddress read (org.omg.CORBA.portable.InputStream istream)
  {
    CHotelServerInterface.CINetSocketAddress value = new CHotelServerInterface.CINetSocketAddress ();
    value.host = istream.read_string ();
    value.port = istream.read_ushort ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CHotelServerInterface.CINetSocketAddress value)
  {
    ostream.write_string (value.host);
    ostream.write_ushort (value.port);
  }

}
