package CHotelServerInterface;


/**
* CHotelServerInterface/CINetSocketAddress.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public final class CINetSocketAddress implements org.omg.CORBA.portable.IDLEntity
{
  public String host = null;
  public short port = (short)0;

  public CINetSocketAddress ()
  {
  } // ctor

  public CINetSocketAddress (String _host, short _port)
  {
    host = _host;
    port = _port;
  } // ctor

} // class CINetSocketAddress
