package CHotelServerInterface;


/**
* CHotelServerInterface/CListSocketsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Sunday, December 6, 2015 9:58:24 PM EST
*/

public final class CListSocketsHolder implements org.omg.CORBA.portable.Streamable
{
  public CHotelServerInterface.CINetSocketAddress value[] = null;

  public CListSocketsHolder ()
  {
  }

  public CListSocketsHolder (CHotelServerInterface.CINetSocketAddress[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CHotelServerInterface.CListSocketsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CHotelServerInterface.CListSocketsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CHotelServerInterface.CListSocketsHelper.type ();
  }

}
