package CHotelServerInterface;

/**
* CHotelServerInterface/CRecordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Friday, November 27, 2015 4:40:26 AM EST
*/

public final class CRecordHolder implements org.omg.CORBA.portable.Streamable
{
  public CHotelServerInterface.CRecord value = null;

  public CRecordHolder ()
  {
  }

  public CRecordHolder (CHotelServerInterface.CRecord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CHotelServerInterface.CRecordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CHotelServerInterface.CRecordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CHotelServerInterface.CRecordHelper.type ();
  }

}
