package CHotelServerInterface;

/**
* CHotelServerInterface/CRoomTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Friday, November 27, 2015 4:40:26 AM EST
*/


// And a convertion utilitity is designed to convert them back and forth
public final class CRoomTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public CHotelServerInterface.CRoomType value = null;

  public CRoomTypeHolder ()
  {
  }

  public CRoomTypeHolder (CHotelServerInterface.CRoomType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CHotelServerInterface.CRoomTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CHotelServerInterface.CRoomTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CHotelServerInterface.CRoomTypeHelper.type ();
  }

}
