package CHotelServerInterface;

/**
* CHotelServerInterface/IHotelCentralAdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Monday, October 26, 2015 6:38:21 PM EDT
*/

public final class IHotelCentralAdminHolder implements org.omg.CORBA.portable.Streamable
{
  public CHotelServerInterface.IHotelCentralAdmin value = null;

  public IHotelCentralAdminHolder ()
  {
  }

  public IHotelCentralAdminHolder (CHotelServerInterface.IHotelCentralAdmin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CHotelServerInterface.IHotelCentralAdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CHotelServerInterface.IHotelCentralAdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CHotelServerInterface.IHotelCentralAdminHelper.type ();
  }

}
