package CHotelServerInterface;


/**
* CHotelServerInterface/IHotelCentralAdminHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Monday, October 26, 2015 6:38:21 PM EDT
*/

abstract public class IHotelCentralAdminHelper
{
  private static String  _id = "IDL:CHotelServerInterface/IHotelCentralAdmin:1.0";

  public static void insert (org.omg.CORBA.Any a, CHotelServerInterface.IHotelCentralAdmin that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CHotelServerInterface.IHotelCentralAdmin extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CHotelServerInterface.IHotelCentralAdminHelper.id (), "IHotelCentralAdmin");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CHotelServerInterface.IHotelCentralAdmin read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IHotelCentralAdminStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CHotelServerInterface.IHotelCentralAdmin value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CHotelServerInterface.IHotelCentralAdmin narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CHotelServerInterface.IHotelCentralAdmin)
      return (CHotelServerInterface.IHotelCentralAdmin)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CHotelServerInterface._IHotelCentralAdminStub stub = new CHotelServerInterface._IHotelCentralAdminStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CHotelServerInterface.IHotelCentralAdmin unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CHotelServerInterface.IHotelCentralAdmin)
      return (CHotelServerInterface.IHotelCentralAdmin)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CHotelServerInterface._IHotelCentralAdminStub stub = new CHotelServerInterface._IHotelCentralAdminStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
