package CHotelServerInterface;


/**
* CHotelServerInterface/IHotelCentralAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CHotelServerInterface.idl
* Monday, October 26, 2015 6:38:21 PM EDT
*/

public interface IHotelCentralAdmin extends IHotelCentralAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IHotelCentralAdmin
